### ISSUE TITLE
stripe.paymentIntents.create not implemented

### ISSUE THREAD

**Issue by arthurchumak** [pushplay/stripe-stateful-mock#12]
Stacktrace
```
No matching path: /v1/payment_intents
  at Function.generate (../../node_modules/stripe/lib/Error.js:40:16)
  at IncomingMessage.<anonymous> (../../node_modules/stripe/lib/StripeResource.js:190:33)
```

**Comment by pushplay** [comment]
Yup.  Payment Intents is a very large undertaking.  A lot of the resources are basic CRUD, but the state here is more complicated.

**Comment by Mihailoff** [comment]
Starting without the state would be a step forward and better than failing requests.

**Comment by pushplay** [comment]
I don't know if I agree.  Having paths that can't store state in a library whose whole purpose is being stateful would be confusing.  People would rightly expect it to be stateful, write tests against it, and then be unhappy when it doesn't work.
